### ISSUE TITLE
Add bundle executable?

### ISSUE THREAD

**Issue by junosuarez** [apanzerj/brakecheck#6]
In a project, we currently run brakeman from a travis script like
```
  bundle exec brakeman -z
  bundle exec rubocop app config lib test
```

It would be nice to be able to add something like
```
  bundle exec brakecheck
  bundle exec brakeman -z
  bundle exec rubocop app config lib test
```

without having to commit another test.rb file

**Comment by apanzerj** [comment]
added here: #7

**Comment by junosuarez** [comment]
Rad, thanks! For reference in this thread, we can now `BRAKECHECK_GEM=brakeman bundle exec brakecheck`

**Comment by apanzerj** [comment]
check latest changes. you should be able to do brakecheck brakeman now.

https://github.com/apanzerj/brakecheck/blob/master/spec/cli_spec.rb
